### PR TITLE
Add support to scan vote key with QR code

### PR DESCRIPTION
**Pull request by tditlu**

### CODE REVIEW

**Comment by Gargaj** [comment]
This only scans the QR code, it doesn't generate it, right?

**Comment by tditlu** [comment]
> This only scans the QR code, it doesn't generate it, right?

Yes, only scans in te register form, doing printing from admin is more work, but it's also possible.

**Comment by tditlu** [comment]
Using something like this on the admin side would enable to print also:
https://github.com/papnkukn/qrcode-svg

**Comment by Gargaj** [comment]
I think getting a code on the votekey is a bit more important; that way you'd be able to have the QR code resolve into an URL that prefills the votekey field -> no JS involved.

The problem is I haven't really found a nice and compact PHP QR generator library yet.

**Comment by tditlu** [comment]
How about this one, single file and PHP 5 support:
https://github.com/kazuhikoarase/qrcode-generator/blob/master/php/qrcode.php

**Pull request closed without merging**
