### PR TITLE
feature: download the compo folder as an archive

### PR DESCRIPTION
**Pull request by 0b5vr**
because the folder layout is perfect for compo setup

it needs php-zip to work

### Points need review

- [ ] How do you think about this feature?
- [ ] It saves a zip archive directly below the `/var/www/entries_private` . Is it valid?
- [ ] Is the implementation and placement of `zip_dir` appropriate?
- [ ] Is the endpoint `http://localhost:8081/compos.php?download=1` appropriate?
- [ ] My English sucks. correct me if it's wrong

### CODE REVIEW

**Comment by Gargaj** [comment]
Why is it downloading the whole folder and not just the selected files?

**Comment by 0b5vr** [comment]
The directory structure inside the `entries_private/<compo>` is very useful to operate compos!, since it's separated by directories with an entry number. it's how we operate compos even before the wuhu era.

**Comment by Gargaj** [comment]
But for internal use, isn't downloading just directly from the server simpler?

**Comment by 0b5vr** [comment]
> But for internal use, isn't downloading just directly from the server simpler?

True, but we couldn't do that in TDF2021 since we didn't have access to the filesystem of the server.
We've used a cloud without SSH or FTP, I know it is completely opposite from your design philosophy though :sweat_smile:

**Comment by Gargaj** [comment]
Honestly this might be one of those cases where banishing this functionality into a plugin might be more worth it, then.

**Comment by 0b5vr** [comment]
mhm! I'll try packing the feature into a plugin

**Comment by 0b5vr** [comment]
Made it a plugin! does it look good?

**Pull request merged**
